"""Committed Session journal envelope and canonical event names (RFC 04)."""

from __future__ import annotations

ENVELOPE_SCHEMA_MAJOR = 1
SCHEMA_VERSION = 1

ENVELOPE_FIELDS = (
    "id",
    "workspace_id",
    "session_id",
    "seq",
    "type",
    "schema_version",
    "recorded_at",
    "observed_at",
    "actor",
    "source",
    "causation_id",
    "correlation_id",
    "turn_id",
    "execution_id",
    "executor_lease_id",
    "lease_generation",
    "delegation_id",
    "changeset_id",
    "delivery_id",
    "runtime_epoch",
    "local_seq",
    "payload",
)

EVENT_TYPES: frozenset[str] = frozenset(
    {
        "session.created",
        "session.settings_changed",
        "session.archived",
        "session.unarchived",
        "session.closed",
        "message.accepted",
        "message.routed",
        "message.part_added",
        "message.part_updated",
        "message.completed",
        "turn.queued",
        "turn.preparing",
        "turn.started",
        "turn.cancel_requested",
        "turn.succeeded",
        "turn.failed",
        "turn.cancelled",
        "turn.interrupted",
        "execution.preparing",
        "execution.started",
        "execution.native_bound",
        "execution.observed_terminal",
        "execution.stopped",
        "tool.started",
        "tool.updated",
        "tool.completed",
        "usage.observed",
        "diagnostic.reported",
        "executor.bound",
        "executor.quiescing",
        "executor.released",
        "executor.unavailable",
        "worktree.restored",
        "worktree.changed",
        "worktree.apply_requested",
        "worktree.applied",
        "snapshot.requested",
        "snapshot.ready",
        "snapshot.failed",
        "changeset.capture_requested",
        "changeset.ready",
        "changeset.capture_failed",
        "delivery.requested",
        "delivery.progressed",
        "delivery.blocked",
        "delivery.succeeded",
        "delivery.failed",
        "delivery.cancelled",
        "delivery.merge_requested",
        "delivery.merged",
        "delivery.merge_failed",
        "delegation.created",
        "delegation.waiting",
        "delegation.result_published",
        "delegation.failed",
        "delegation.cancel_requested",
        "delegation.cancelled",
        "service.requested",
        "service.ready",
        "service.degraded",
        "service.failed",
        "service.stopped",
    }
)


def is_known(event_type: str) -> bool:
    return event_type in EVENT_TYPES
