name = "sbx-hosted-alpha"
compatibility_date = "2026-10-01"
workers_dev = false

[assets]
directory = "../../console/dist"
not_found_handling = "single-page-application"

[[routes]]
pattern = "sbx-agent.com"
custom_domain = true
