#!/usr/bin/env python3
"""Stub runner implementing docs/contracts/runner-cli.md for local tests."""

from __future__ import annotations

import argparse
import json
import os
import signal
import sys
import time
from pathlib import Path

FIXTURE_DIR = Path(__file__).resolve().parent.parent / "fixtures" / "events"
DEFAULT_THREAD_ID = "01a09a36-b4fb-7f90-b96e-42adeefa05e0"

EXIT_OK = 0
EXIT_CODEX = 2
EXIT_TIMEOUT = 3
EXIT_BAD_JSON = 4


def work_root() -> Path:
    raw = os.environ.get("SBX_WORK")
    if not raw:
        print("SBX_WORK is required", file=sys.stderr)
        sys.exit(1)
    return Path(raw)


def codex_home(root: Path) -> Path:
    return Path(os.environ.get("CODEX_HOME", str(root / ".codex")))


def pid_file(root: Path) -> Path:
    return root / "runner.pid"


def _pid_alive(pid: int) -> bool:
    try:
        os.kill(pid, 0)
    except ProcessLookupError:
        return False
    except PermissionError:
        return True
    return True


def turn_in_progress(root: Path) -> bool:
    path = pid_file(root)
    if not path.is_file():
        return False
    try:
        pid = int(path.read_text(encoding="utf-8").strip())
    except ValueError:
        return False
    return _pid_alive(pid)


def emit(root: Path, obj: dict) -> None:
    line = json.dumps(obj, ensure_ascii=False)
    events = root / "events.jsonl"
    with events.open("a", encoding="utf-8") as fh:
        fh.write(line + "\n")
    print(line, flush=True)


def emit_raw(root: Path, line: str) -> None:
    events = root / "events.jsonl"
    with events.open("a", encoding="utf-8") as fh:
        fh.write(line + "\n")
    print(line, flush=True)


def cmd_init(args: argparse.Namespace) -> int:
    root = work_root()
    root.mkdir(parents=True, exist_ok=True)
    (root / "inbox").mkdir(exist_ok=True)
    (root / "turns").mkdir(exist_ok=True)
    home = codex_home(root)
    home.mkdir(parents=True, exist_ok=True)

    (home / "config.toml").write_text(
        (
            f'model = "{args.model}"\n'
            'approval_policy = "never"\n'
            'sandbox_mode = "danger-full-access"\n'
            "\n"
            "[shell_environment_policy]\n"
            'exclude = ["CODEX_AUTH_JSON"]\n'
        ),
        encoding="utf-8",
    )

    src_auth = root / "auth.json"
    if args.auth == "auth_json" and src_auth.is_file():
        payload = json.loads(src_auth.read_text(encoding="utf-8"))
    elif args.auth == "auth_json":
        payload = {
            "auth_mode": "auth_json",
            "tokens": {
                "access_token": "REDACTED",
                "refresh_token": "REDACTED",
                "id_token": "REDACTED",
            },
        }
    else:
        payload = {
            "auth_mode": "provider",
            "provider": "chatgpt",
            "tokens": {"access_token": "REDACTED"},
        }
    _redact_tokens(payload)
    auth_path = home / "auth.json"
    auth_path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    auth_path.chmod(0o600)

    (root / "AGENTS.md").write_text(
        "# Sandbox AGENTS.md\n\nGenerated by `runner init`. Do not put secrets here.\n",
        encoding="utf-8",
    )
    (root / "events.jsonl").write_text("", encoding="utf-8")
    (root / "session.json").write_text(
        json.dumps({"codex_session_id": None, "turn": 0}) + "\n",
        encoding="utf-8",
    )
    return EXIT_OK


def _redact_tokens(obj: object) -> None:
    if isinstance(obj, dict):
        for key, value in obj.items():
            if key in {"access_token", "refresh_token", "id_token", "token", "api_key", "password"}:
                obj[key] = "REDACTED"
            else:
                _redact_tokens(value)
    elif isinstance(obj, list):
        for item in obj:
            _redact_tokens(item)


def _scenario() -> str:
    return os.environ.get("FAKE_CODEX_SCENARIO", "success")


def _load_session(root: Path) -> dict:
    path = root / "session.json"
    if not path.is_file():
        return {"codex_session_id": None, "turn": 0}
    return json.loads(path.read_text(encoding="utf-8"))


def _write_session(root: Path, session: dict) -> None:
    (root / "session.json").write_text(json.dumps(session) + "\n", encoding="utf-8")


def cmd_turn(args: argparse.Namespace) -> int:
    root = work_root()
    if turn_in_progress(root):
        emit(root, {"type": "sbx.error", "message": "turn already in progress"})
        return EXIT_CODEX
    start = time.monotonic()
    pid_file(root).write_text(str(os.getpid()), encoding="utf-8")

    def _on_term(_signum: int, _frame: object) -> None:
        sys.exit(EXIT_OK)

    signal.signal(signal.SIGTERM, _on_term)
    signal.signal(signal.SIGINT, _on_term)

    inbox = root / "inbox"
    inbox.mkdir(exist_ok=True)
    (root / "turns").mkdir(exist_ok=True)
    message = Path(args.message_file).read_text(encoding="utf-8")
    (inbox / f"{args.n}.md").write_text(message, encoding="utf-8")

    emit(root, {"type": "sbx.turn_started", "n": args.n})

    scenario = _scenario()
    fixture = FIXTURE_DIR / f"{scenario}.jsonl"
    if not fixture.is_file():
        emit(root, {"type": "sbx.error", "message": f"missing fixture {scenario}"})
        return EXIT_BAD_JSON

    usage = {"input_tokens": 0, "cached_input_tokens": 0, "output_tokens": 0}
    thread_id = _load_session(root).get("codex_session_id") or DEFAULT_THREAD_ID
    last_message = ""
    timed_out = False
    bad_json = False

    lines = fixture.read_text(encoding="utf-8").splitlines()
    for index, raw in enumerate(lines):
        if time.monotonic() - start >= args.max_seconds:
            timed_out = True
            break
        stripped = raw.strip()
        if not stripped:
            continue
        if scenario == "slow" and index == 1:
            delay = float(os.environ.get("FAKE_CODEX_SLOW_SECONDS", "40"))
            remaining = args.max_seconds - (time.monotonic() - start)
            time.sleep(min(delay, max(0.0, remaining)))
            if time.monotonic() - start >= args.max_seconds:
                timed_out = True
                emit_raw(root, stripped)
                break
        emit_raw(root, stripped)
        try:
            obj = json.loads(stripped)
        except json.JSONDecodeError:
            bad_json = True
            emit(root, {"type": "sbx.error", "message": "bad json in event stream"})
            continue
        if obj.get("type") == "thread.started" and obj.get("thread_id"):
            thread_id = obj["thread_id"]
        if obj.get("type") == "turn.completed" and isinstance(obj.get("usage"), dict):
            usage = {
                "input_tokens": int(obj["usage"].get("input_tokens", 0)),
                "cached_input_tokens": int(obj["usage"].get("cached_input_tokens", 0)),
                "output_tokens": int(obj["usage"].get("output_tokens", 0)),
            }
            for opt in ("cache_write_input_tokens", "reasoning_output_tokens"):
                if opt in obj["usage"]:
                    usage[opt] = int(obj["usage"][opt])
        item = obj.get("item")
        if isinstance(item, dict) and item.get("type") == "agent_message" and item.get("text"):
            last_message = item["text"]
        if scenario == "hang" and index == 0:
            remaining = args.max_seconds - (time.monotonic() - start)
            time.sleep(max(0.0, remaining if remaining < 3600 else 3600))
            if time.monotonic() - start >= args.max_seconds:
                timed_out = True
            break

    duration = round(time.monotonic() - start, 3)
    session = _load_session(root)
    session["codex_session_id"] = thread_id
    session["turn"] = args.n
    _write_session(root, session)

    if timed_out:
        status = "timeout"
        code = EXIT_TIMEOUT
    elif bad_json:
        status = "bad_json"
        code = EXIT_BAD_JSON
    elif scenario == "nonzero":
        status = "codex_error"
        code = EXIT_CODEX
    else:
        status = "success"
        code = EXIT_OK

    emit(
        root,
        {
            "type": "sbx.turn_finished",
            "n": args.n,
            "status": status,
            "exit_code": code,
            "duration_s": duration,
            "usage": usage,
        },
    )
    turn_path = root / "turns" / f"{args.n}.json"
    turn_path.write_text(
        json.dumps(
            {
                "n": args.n,
                "codex_session_id": thread_id,
                "status": status,
                "usage": usage,
                "message": last_message,
                "exit_code": code,
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    try:
        pid_file(root).unlink(missing_ok=True)
    except TypeError:
        if pid_file(root).exists():
            pid_file(root).unlink()
    return code


def cmd_stop(_args: argparse.Namespace) -> int:
    root = work_root()
    path = pid_file(root)
    if not path.is_file():
        return EXIT_OK
    try:
        pid = int(path.read_text(encoding="utf-8").strip())
    except ValueError:
        return EXIT_OK
    try:
        os.kill(pid, signal.SIGTERM)
    except ProcessLookupError:
        pass
    return EXIT_OK


def main() -> None:
    parser = argparse.ArgumentParser(prog="runner")
    sub = parser.add_subparsers(dest="cmd", required=True)

    p_init = sub.add_parser("init")
    p_init.add_argument("--auth", required=True, choices=["auth_json", "provider"])
    p_init.add_argument("--model", required=True)

    p_turn = sub.add_parser("turn")
    p_turn.add_argument("--n", type=int, required=True)
    p_turn.add_argument("--message-file", required=True)
    p_turn.add_argument("--max-seconds", type=int, default=900)

    sub.add_parser("stop")

    args = parser.parse_args()
    if args.cmd == "init":
        code = cmd_init(args)
    elif args.cmd == "turn":
        code = cmd_turn(args)
    else:
        code = cmd_stop(args)
    raise SystemExit(code)


if __name__ == "__main__":
    main()
