from contextlib import AbstractContextManager
from typing import Any, Protocol


class Repository(Protocol):
    def one(self, sql: str, args: tuple = ()) -> dict[str, Any] | None: ...
    def all(self, sql: str, args: tuple = ()) -> list[dict[str, Any]]: ...
    def execute(self, sql: str, args: tuple = ()) -> None: ...
    def event(self, workspace: str, session: str, kind: str, payload: dict, **refs) -> int: ...
    def enqueue(self, workspace: str, kind: str, target: str, identity: str) -> str: ...


class UnitOfWork(Protocol):
    def transaction(self) -> AbstractContextManager[Repository]: ...


class Vault(Protocol):
    def encrypt(self, payload: dict, context: dict) -> dict: ...
    def decrypt(self, envelope: dict, context: dict) -> dict: ...


class BlobStore(Protocol):
    def put(self, workspace: str, content: bytes) -> str: ...
    def get(self, workspace: str, key: str) -> bytes: ...
