"""Generate/check the business OpenAPI contract and shared TS request schemas."""

import argparse
import json
from pathlib import Path
from types import SimpleNamespace

from control.api.app import create_app


def ts(schema):
    if not isinstance(schema, dict):
        return "unknown"
    if "$ref" in schema:
        return schema["$ref"].split("/")[-1]
    if "anyOf" in schema:
        return " | ".join(ts(s) for s in schema["anyOf"])
    if "enum" in schema:
        return " | ".join(json.dumps(s) for s in schema["enum"])
    kind = schema.get("type")
    if kind == "object":
        fields = schema.get("properties")
        if fields:
            return (
                "{ "
                + "; ".join(
                    k + ("" if k in schema.get("required", []) else "?") + ": " + ts(v)
                    for k, v in fields.items()
                )
                + " }"
            )
        return "Record<string, " + ts(schema.get("additionalProperties", {})) + ">"
    if kind == "array":
        return "(" + ts(schema["items"]) + ")[]"
    return {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "null": "null",
    }.get(kind, "unknown")


def generate():
    import yaml

    schema = create_app(SimpleNamespace(uow=None, master=b"REDACTED")).openapi()
    definitions = schema["components"]["schemas"]
    types = "// Generated by scripts/unified_spec.py. Do not edit.\n" + "".join(
        "export type " + name + " = " + ts(value) + ";\n"
        for name, value in sorted(definitions.items())
    )
    from control.api.schemas import EventView, ResultContract
    from protocol.runtime import OperationFrame

    auxiliary = {
        "events": EventView.model_json_schema(),
        "result": ResultContract.model_json_schema(),
        "runtime": OperationFrame.model_json_schema(),
    }
    return {
        **{
            "docs/specs/unified/" + name + ".schema.json": json.dumps(
                value, sort_keys=True, indent=2
            )
            + "\n"
            for name, value in auxiliary.items()
        },
        "docs/specs/unified/openapi.yaml": yaml.safe_dump(
            schema, sort_keys=True, allow_unicode=True
        ),
        "console/src/api/generated.ts": types,
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for name, contents in generate().items():
        path = Path(name)
        if args.check:
            if not path.exists() or path.read_text() != contents:
                raise SystemExit("API drift: " + name)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(contents)


if __name__ == "__main__":
    main()
